services:
  nginx:
    image: nginx:stable
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./nginx/default.temp.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    # entrypoint: >
    #   /bin/sh -c "trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done"

  backend:
    build: .
    restart: unless-stopped
    env_file: ./.env
    depends_on:
      - mongo
    expose:
      - "3000"

  mongo:
    image: mongo:5.0
    restart: unless-stopped
    volumes:
      - ./mongo-data:/data/db
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: tutorioBotAdmin
      MONGO_INITDB_ROOT_PASSWORD: sm10_mvg54sljd4hssgv54vn
